// Expo config plugin: inject a release signing config into the Gradle project
// generated by `expo prebuild`.
//
// Because `android/` is regenerated on every prebuild (it is gitignored), the
// signing setup can't be hand-edited into build.gradle — it would be wiped on
// the next run. This plugin patches the generated app/build.gradle during
// prebuild so the config survives every regeneration.
//
// Credentials are read from Gradle properties at build time (never committed):
//   MYAPP_RELEASE_STORE_FILE      path to the keystore
//   MYAPP_RELEASE_STORE_PASSWORD  keystore (store) password
//   MYAPP_RELEASE_KEY_ALIAS       key alias
//   MYAPP_RELEASE_KEY_PASSWORD    key password
// CI supplies these via -P flags (sourced from GitHub secrets).
//
// When those properties are absent (a local `assembleRelease` with no keystore),
// the release build falls back to debug signing so the build still succeeds —
// only CI produces a properly-signed, Obtainium-installable APK.
//
// Additionally, versionCode and versionName become overridable via Gradle
// properties so CI can drive versionCode from the run number (must strictly
// increase or Android refuses the update) and versionName from the release tag.

const { withAppBuildGradle } = require('@expo/config-plugins')

const RELEASE_SIGNING_CONFIG = `        release {
            if (project.hasProperty('MYAPP_RELEASE_STORE_FILE')) {
                storeFile file(MYAPP_RELEASE_STORE_FILE)
                storePassword MYAPP_RELEASE_STORE_PASSWORD
                keyAlias MYAPP_RELEASE_KEY_ALIAS
                keyPassword MYAPP_RELEASE_KEY_PASSWORD
            }
        }
`

function patchSigningConfigs(contents) {
  if (contents.includes('release {\n            if (project.hasProperty')) {
    return contents // already patched
  }
  // Insert a `release` block immediately after the `debug { ... }` entry inside
  // `signingConfigs { ... }`. Anchor on the closing brace of the debug block.
  const anchor = /(signingConfigs \{\s*\n\s*debug \{[\s\S]*?\n        \}\n)/
  if (!anchor.test(contents)) {
    throw new Error(
      'withReleaseSigning: could not find signingConfigs.debug anchor in build.gradle — Expo template changed, plugin needs updating',
    )
  }
  return contents.replace(anchor, `$1${RELEASE_SIGNING_CONFIG}`)
}

function patchReleaseBuildType(contents) {
  // Point the release buildType at the release signing config when a keystore
  // property is present, otherwise keep debug signing (local builds).
  //
  // The release buildType's `signingConfig signingConfigs.debug` is uniquely
  // identified by being immediately followed by `shrinkResources` — the debug
  // buildType has no such line. Anchoring on that avoids accidentally patching
  // the debug buildType.
  const anchor = /signingConfig signingConfigs\.debug(\n\s*shrinkResources)/
  if (!anchor.test(contents)) {
    throw new Error(
      'withReleaseSigning: could not find release buildType signingConfig anchor — Expo template changed, plugin needs updating',
    )
  }
  return contents.replace(
    anchor,
    `signingConfig project.hasProperty('MYAPP_RELEASE_STORE_FILE') ? signingConfigs.release : signingConfigs.debug$1`,
  )
}

function patchVersionCode(contents) {
  // Make versionCode overridable from a Gradle property so CI can pass the run
  // number. Falls back to the literal from app.json when unset.
  return contents.replace(
    /versionCode \d+/,
    "versionCode (findProperty('versionCode')?.toInteger() ?: $&)".replace(
      '$&',
      contents.match(/versionCode (\d+)/)?.[1] ?? '1',
    ),
  )
}

function patchVersionName(contents) {
  // Make versionName overridable from a Gradle property so CI can set it from
  // the release tag (the app otherwise always shows app.json's version). Falls
  // back to the literal from app.json when unset.
  const current = contents.match(/versionName "([^"]+)"/)?.[1] ?? '1.0.0'
  return contents.replace(
    /versionName "[^"]+"/,
    `versionName (findProperty('versionName') ?: "${current}")`,
  )
}

module.exports = function withReleaseSigning(config) {
  return withAppBuildGradle(config, (cfg) => {
    if (cfg.modResults.language !== 'groovy') {
      throw new Error(
        'withReleaseSigning: expected groovy build.gradle, got ' + cfg.modResults.language,
      )
    }
    let contents = cfg.modResults.contents
    contents = patchSigningConfigs(contents)
    contents = patchReleaseBuildType(contents)
    contents = patchVersionCode(contents)
    contents = patchVersionName(contents)
    cfg.modResults.contents = contents
    return cfg
  })
}
