// The source of the compiled binary's entry point (#288), which `scripts/build-binary.ts`
// writes to `dist/entry.ts` and compiles.
//
// Every file of the frontend build is named in it by its own import, rather than handed to the
// bundler as a directory: Bun's directory embedding has dropped files (L01, oven-sh/bun#23852),
// and a missing chunk would surface only when someone clicked into that page. An import that
// cannot be resolved fails the build instead. The migrations ride along as strings, because a
// binary has no folder to read them from.

import type { Migration } from '../db/sqlite/migrate'

/** A file to embed: the path it is served at, and where it is, relative to the entry. */
export type EmbeddedFile = { servedAs: string; source: string }

// Bun reads `?` and `#` in a specifier as a query or a fragment, not as part of the name.
const SAFE_SOURCE = /^\.\.?\/[\w@+\-./]+$/

export function binaryEntrySource(
  files: readonly EmbeddedFile[],
  migrations: readonly Migration[],
  launcher: string,
): string {
  if (!files.some((f) => f.servedAs === '/index.html')) {
    throw new Error('the frontend build has no index.html')
  }
  const imports = files.map((f, i) => {
    if (!SAFE_SOURCE.test(f.source) || !f.servedAs.startsWith('/')) {
      throw new Error(`cannot embed ${JSON.stringify(f.source)} as ${JSON.stringify(f.servedAs)}`)
    }
    return `import f${i} from ${JSON.stringify(f.source)} with { type: 'file' }`
  })
  const entries = files.map((f, i) => `  [${JSON.stringify(f.servedAs)}, f${i}],`)
  return [
    '// Generated by scripts/build-binary.ts (#288) on every build. Do not edit.',
    `import { launchLocal } from ${JSON.stringify(launcher)}`,
    ...imports,
    '',
    'const files = new Map<string, string>([',
    ...entries,
    '])',
    `const migrations = ${JSON.stringify(migrations, null, 2)}`,
    '',
    'await launchLocal({ frontend: { files }, migrations })',
    '',
  ].join('\n')
}
